# -*- coding: utf-8 -*-
"""appppp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfMWQxPJmgQ9IFfLQrBEDk1gFyTdqZp7
"""

# -*- coding: utf-8 -*-
"""
DSS Penjadwalan Produksi Job Shop - Garmen
Versi Perbaikan (Fixed):
  - [FIX 1] Stasiun '7. Inspeksi_QC' dihapus dari STATIONS (tidak ada di pabrik)
  - [FIX 2] SA: acceptance probability diperbaiki (current_score, bukan best_score)
  - [FIX 3] SA: iterasi dinaikkan 500 → 8000, cooling 0.95 → 0.997 (pendinginan lambat)
  - [FIX 4] SA: tambah neighbourhood operator 'insert' selain 'swap' agar lebih variatif
  - [FIX 5] MILP: BigM dihitung dinamis (2 × estimasi makespan), bukan hardcode 1_000_000
  - [FIX 6] MILP: perbandingan pemenang menerima status 'Optimal' DAN 'Feasible'
  - [FIX 7] hitung_target_menit: deadline dihitung sampai menit jam 17:30 hari due date,
            bukan selalu +450 menit penuh untuk hari terakhir
  - [FIX 8] MILP variable T direname → Tard_var agar tidak bentrok dengan Python built-in T
"""

import streamlit as st
import pandas as pd
import pulp
import math
import random
import io
from datetime import datetime, timedelta
import plotly.express as px

# ==========================================
# 1. KONFIGURASI HALAMAN & STATE
# ==========================================
st.set_page_config(page_title="DSS Penjadwalan Job Shop", layout="wide", page_icon="🏭")

st.markdown("""
    <style>
    .main-header { font-size: 2.5rem; font-weight: 700; color: #1E3A8A; margin-bottom: 0px; }
    .sub-header { font-size: 1.2rem; color: #64748B; margin-bottom: 20px; }
    .metric-card { background-color: #F8FAFC; border-radius: 10px; padding: 20px; border: 1px solid #E2E8F0; }
    </style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-header">🏭 DSS: Optimasi Penjadwalan Produksi</p>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">Sistem Penjadwalan Cerdas dengan Routing Dinamis (OPC), Dual-Engine Optimizer (SA + MILP), dan Analisis Sensitivitas.</p>', unsafe_allow_html=True)
st.divider()

# [FIX 1] '7. Inspeksi_QC' DIHAPUS — stasiun ini tidak ada di pabrik
STATIONS = [
    '1. Potong', '2. Jahit_KaosPolo', '3. Jahit_KemejaJaket',
    '4. Sablon', '5. DTF', '6. Bordir',
    '7. Pasang_Kancing', '8. Buang_Benang', '9. Lipat', '10. Packing'
]

REQUIRED_COLUMNS = [
    'id pesanan', 'jenis produk', 'qty', 'due date (tanggal)',
    'furing', 'sablon', 'dtf', 'bordir', 'pasang kancing'
]

BINARY_COLUMNS = ['furing', 'sablon', 'dtf', 'bordir', 'pasang kancing']


# ==========================================
# 2. HELPER: LOAD & CLEAN DATA
# ==========================================
def load_order_file(uploaded_file):
    file_name = uploaded_file.name.lower()

    if file_name.endswith('.csv'):
        df = pd.read_csv(uploaded_file)
    elif file_name.endswith('.xlsx') or file_name.endswith('.xls'):
        df = pd.read_excel(uploaded_file)
    else:
        raise ValueError("Format file tidak didukung. Gunakan CSV atau Excel.")

    df.columns = df.columns.str.lower().str.strip()

    missing_cols = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Kolom berikut belum ada / salah nama: {missing_cols}")

    df = df[REQUIRED_COLUMNS].copy()

    df['id pesanan'] = df['id pesanan'].astype(str).str.strip()
    df['jenis produk'] = df['jenis produk'].astype(str).str.strip().str.lower()

    mapping_jenis = {'kaos': 'kaos', 'polo': 'polo', 'kemeja': 'kemeja', 'jaket': 'jaket'}
    df['jenis produk'] = df['jenis produk'].replace(mapping_jenis)

    unknown_jenis = sorted(set(df['jenis produk']) - set(mapping_jenis.values()))
    if unknown_jenis:
        raise ValueError(f"Jenis produk tidak dikenali: {unknown_jenis}")

    df['qty'] = pd.to_numeric(df['qty'], errors='coerce')

    for col in BINARY_COLUMNS:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df['due date (tanggal)'] = pd.to_datetime(
        df['due date (tanggal)'], errors='coerce', dayfirst=True
    )

    if df[['id pesanan', 'jenis produk', 'qty', 'due date (tanggal)'] + BINARY_COLUMNS].isnull().any().any():
        bad_rows = df[df[['qty', 'due date (tanggal)'] + BINARY_COLUMNS].isnull().any(axis=1)]
        raise ValueError(
            "Ada data kosong / invalid setelah dibaca. "
            "Cek terutama kolom qty, due date (tanggal), dan kolom 0/1.\n"
            f"Baris bermasalah: {bad_rows.index.tolist()}"
        )

    if (df['qty'] <= 0).any():
        bad_ids = df.loc[df['qty'] <= 0, 'id pesanan'].tolist()
        raise ValueError(f"Ada qty <= 0 pada order: {bad_ids}")

    for col in BINARY_COLUMNS:
        invalid_vals = df.loc[~df[col].isin([0, 1]), col].unique().tolist()
        if invalid_vals:
            raise ValueError(f"Kolom '{col}' hanya boleh berisi 0 atau 1. Nilai invalid: {invalid_vals}")

    return df


# ==========================================
# 3. LOGIKA KAPASITAS & WAKTU PROSES
# ==========================================
def hitung_waktu_proses(row, resources, setup_time):
    qty   = row['qty']
    jenis = str(row['jenis produk']).lower()
    furing = row['furing']

    # Semua stasiun diinisialisasi 0 (ghost bottleneck prevention)
    P = {m: 0.0 for m in STATIONS}

    # --- 1. Potong ---
    cap_potong = 1000
    if jenis in ['kemeja', 'jaket']:
        cap_potong = 125 if furing == 1 else 250
    P['1. Potong'] = (qty / (cap_potong * resources['1. Potong'])) * 450

    # --- 2/3. Jahit (mutual exclusive berdasarkan jenis produk) ---
    if jenis in ['kaos', 'polo']:
        cap_jahit = 112.5 if jenis == 'kaos' else 55
        P['2. Jahit_KaosPolo'] = (qty / (cap_jahit * resources['2. Jahit_KaosPolo'])) * 450
    elif jenis in ['kemeja', 'jaket']:
        base_cap = 13.5 if jenis == 'kemeja' else 11.0
        if furing == 1:
            base_cap *= (2 / 3)
        P['3. Jahit_KemejaJaket'] = (qty / (base_cap * resources['3. Jahit_KemejaJaket'])) * 450

    # --- Proses tambahan (opsional, berdasarkan flag biner) ---
    if row['sablon'] == 1:
        P['4. Sablon'] = (qty / (700 * resources['4. Sablon'])) * 450
    if row['dtf'] == 1:
        P['5. DTF'] = (qty / (750 * resources['5. DTF'])) * 450
    if row['bordir'] == 1:
        P['6. Bordir'] = (qty / (442.5 * resources['6. Bordir'])) * 450

    # --- Pasang kancing (kaos tidak punya kancing) ---
    if row['pasang kancing'] == 1 and jenis != 'kaos':
        cap_kancing = 400 if jenis == 'polo' else 125
        P['7. Pasang_Kancing'] = (qty / (cap_kancing * resources['7. Pasang_Kancing'])) * 450

    # --- Finishing (selalu ada) ---
    cap_benang = 166.67 if furing == 1 else 500
    P['8. Buang_Benang'] = (qty / (cap_benang * resources['8. Buang_Benang'])) * 450
    P['9. Lipat']        = (qty / (500 * resources['9. Lipat'])) * 450
    P['10. Packing']     = (qty / (500 * resources['10. Packing'])) * 450

    # Setup time hanya ditambahkan ke stasiun yang aktif (P > 0)
    for m in STATIONS:
        if P[m] > 0:
            P[m] += setup_time

    return P


# ==========================================
# 4. KONVERSI WAKTU (MENIT EFEKTIF → JAM DINDING)
# ==========================================
def konversi_ke_jam_dinding(menit_efektif, start_date):
    """
    Konversi menit efektif (skipping Minggu & istirahat 11:30-13:00)
    ke datetime jam dinding nyata.
    Asumsi: 450 menit efektif / hari (08:30-11:30 = 180 menit, 13:00-17:30 = 270 menit)
    """
    hari_ke    = int(menit_efektif // 450)
    sisa_menit = menit_efektif % 450

    current_date  = start_date
    hari_tambahan = 0

    while hari_tambahan < hari_ke:
        current_date  += timedelta(days=1)
        if current_date.weekday() != 6:   # skip Minggu
            hari_tambahan += 1

    # Kalau landing di Minggu, geser ke Senin
    if current_date.weekday() == 6:
        current_date += timedelta(days=1)

    # sisa_menit 0–179 → sesi pagi (08:30–11:30)
    # sisa_menit 180–449 → sesi siang (13:00–17:30), skip 90 menit istirahat
    if sisa_menit <= 180:
        return current_date.replace(hour=8, minute=30, second=0, microsecond=0) + timedelta(minutes=sisa_menit)
    else:
        return current_date.replace(hour=8, minute=30, second=0, microsecond=0) + timedelta(minutes=sisa_menit + 90)


def pecah_balok_gantt(start_efektif, durasi, start_date):
    """
    Memecah blok jadwal agar tidak menembus istirahat (menit ke-180 dalam sehari)
    dan pergantian hari (menit ke-450 dalam sehari).
    """
    blocks         = []
    menit_tersisa  = durasi
    current_efektif = start_efektif

    while menit_tersisa > 0.01:
        menit_di_hari = current_efektif % 450
        if menit_di_hari < 180:
            chunk = min(menit_tersisa, 180 - menit_di_hari)
        else:
            chunk = min(menit_tersisa, 450 - menit_di_hari)

        if chunk < 0.01:
            # Tepat di batas — loncat ke segmen berikutnya
            current_efektif += 0.01
            continue

        blocks.append({
            'start_nyata'    : konversi_ke_jam_dinding(current_efektif, start_date),
            'end_nyata'      : konversi_ke_jam_dinding(current_efektif + chunk, start_date),
            'durasi_potongan': chunk
        })

        current_efektif += chunk
        menit_tersisa   -= chunk

    return blocks


# ==========================================
# 5. KONVERSI DUE DATE → MENIT EFEKTIF
# [FIX 7] Deadline dihitung sampai persis jam 17:30 hari due date,
#          bukan selalu menambahkan 450 menit penuh.
# ==========================================
def hitung_target_menit(target_dt, start_dt):
    """
    Menghitung jumlah menit efektif (skip Minggu & istirahat) dari start_dt ke target_dt.
    target_dt sudah di-set ke jam 17:30 pada hari due date.
    """
    if target_dt <= start_dt:
        return 0

    total_menit = 0
    current     = start_dt

    # Hitung hari-hari penuh antara start dan due date
    while current.date() < target_dt.date():
        if current.weekday() != 6:   # skip Minggu
            total_menit += 450       # 1 hari kerja penuh = 450 menit efektif
        current += timedelta(days=1)

    # Pada hari due date, hitung hanya sampai jam 17:30 (= 450 menit efektif penuh hari itu)
    # Karena jam tutup pabrik = 17:30, dan target_dt sudah di-set 17:30,
    # maka hari terakhir = 450 menit penuh (jika bukan Minggu)
    if target_dt.weekday() != 6:
        # Hitung menit efektif dari awal hari kerja (08:30) sampai target_dt (17:30)
        # Sesi pagi: 08:30-11:30 = 180 menit; Sesi siang: 13:00-17:30 = 270 menit
        # Total = 450 menit. Tapi kalau due date jam 17:30 persis = 450 menit penuh.
        menit_di_hari_terakhir = 0
        jam_mulai_hari = current.replace(hour=8, minute=30, second=0, microsecond=0)

        if target_dt >= jam_mulai_hari:
            # Menit kalender dari 08:30 ke target_dt
            delta_kalender = (target_dt - jam_mulai_hari).total_seconds() / 60
            if delta_kalender <= 180:
                # Masih di sesi pagi
                menit_di_hari_terakhir = delta_kalender
            elif delta_kalender <= 270:
                # Di jeda istirahat — kunci ke 180 (akhir sesi pagi)
                menit_di_hari_terakhir = 180
            else:
                # Sesi siang: kurangi 90 menit istirahat
                menit_di_hari_terakhir = delta_kalender - 90

        total_menit += menit_di_hari_terakhir

    return total_menit


# ==========================================
# 6. SANITY CHECK
# ==========================================
def jalankan_sanity_check(jadwal_final):
    log = []
    log.append("============================================================")
    log.append("🔍 [SYSTEM LOG] MEMULAI SANITY CHECK (VERIFIKASI LOGIKA)")
    log.append("============================================================\n")

    err_overlap, err_presedens = False, False

    log.append("[1/3] Memeriksa Overlap Kapasitas Mesin...")
    stasiun_list = set([t['m'] for t in jadwal_final])
    for st_name in stasiun_list:
        tugas_st = sorted([t for t in jadwal_final if t['m'] == st_name], key=lambda x: x['start'])
        for i in range(1, len(tugas_st)):
            prev, curr = tugas_st[i - 1], tugas_st[i]
            if round(curr['start'] - (prev['start'] + prev['dur']), 2) < -0.01:
                log.append(f"  ❌ OVERLAP di {st_name}: Order {prev['job']} & {curr['job']} bentrok!")
                err_overlap = True
    if not err_overlap:
        log.append("  ✔️ LULUS: Tidak ada order tumpang tindih.")

    log.append("\n[2/3] Memeriksa Presedensi (Urutan Stasiun per Pesanan)...")
    job_list = set([t['job'] for t in jadwal_final])
    for job in job_list:
        tugas_job = sorted([t for t in jadwal_final if t['job'] == job], key=lambda x: x['start'])
        for i in range(1, len(tugas_job)):
            prev, curr = tugas_job[i - 1], tugas_job[i]
            if round(curr['start'] - (prev['start'] + prev['dur']), 2) < -0.01:
                log.append(f"  ❌ ERROR URUTAN Order {job}: {curr['m']} mulai sebelum {prev['m']} selesai!")
                err_presedens = True
    if not err_presedens:
        log.append("  ✔️ LULUS: Seluruh urutan pengerjaan sudah benar.")

    log.append("\n[3/3] Memeriksa Pelanggaran Istirahat & Libur...")
    log.append("  ✔️ LULUS: Konversi waktu menjamin tidak ada jadwal aktif di jam istirahat/hari libur.")

    log.append("\n============================================================")
    if err_overlap or err_presedens:
        log.append("🚨 SANITY CHECK GAGAL! Ditemukan pelanggaran.")
    else:
        log.append("✅ SANITY CHECK PASSED! Rute Dinamis & Jadwal Valid.")
    log.append("============================================================")

    return "\n".join(log)


# ==========================================
# 7. SIMULATED ANNEALING (VERSI DIPERBAIKI)
# [FIX 2] Acceptance probability menggunakan current_score (bukan best_score)
# [FIX 3] Iterasi 8000, cooling 0.997 (pendinginan lambat agar eksplorasi lebih luas)
# [FIX 4] Neighbourhood: 70% swap, 30% insert (lebih variatif)
# ==========================================
def run_simulated_annealing(jobs, P_dict, D_dict, W_dict):

    def eval_sequence(seq):
        """
        Evaluasi jadwal dengan dispatcher sederhana:
        Untuk setiap job (berurutan sesuai seq), jadwalkan tiap stasiun aktif
        setelah stasiun sebelumnya (di job yang sama) dan setelah mesin itu bebas.
        """
        m_avail = {m: 0.0 for m in STATIONS}
        j_avail = {j: 0.0 for j in seq}
        total_penalti = 0
        schedule = []

        for j in seq:
            rute_aktif = [m for m in STATIONS if P_dict[j][m] > 0]
            for m in rute_aktif:
                dur   = P_dict[j][m]
                start = max(m_avail[m], j_avail[j])
                end   = start + dur
                m_avail[m] = end
                j_avail[j] = end
                schedule.append({'job': j, 'm': m, 'start': start, 'dur': dur})

            tard = max(0, j_avail[j] - D_dict[j])
            total_penalti += tard * W_dict[j]

        return total_penalti, schedule, j_avail

    def neighbour_swap(seq):
        """Tukar posisi dua job secara acak."""
        new_seq = seq.copy()
        i, j = random.sample(range(len(new_seq)), 2)
        new_seq[i], new_seq[j] = new_seq[j], new_seq[i]
        return new_seq

    def neighbour_insert(seq):
        """Cabut satu job dari posisinya, sisipkan di posisi acak lain."""
        new_seq = seq.copy()
        i = random.randrange(len(new_seq))
        job = new_seq.pop(i)
        j = random.randrange(len(new_seq) + 1)
        new_seq.insert(j, job)
        return new_seq

    # --- Inisialisasi: urutan awal = EDD (Earliest Due Date) ---
    current_seq   = sorted(jobs, key=lambda x: D_dict[x])
    current_score, _, _ = eval_sequence(current_seq)
    best_seq      = current_seq.copy()
    best_score    = current_score

    # [FIX 3] Parameter SA yang diperbaiki
    T_sa          = 500.0    # suhu awal — disesuaikan ke skala penalti
    cooling_rate  = 0.997    # pendinginan sangat lambat (dulu 0.95)
    n_iter        = 8000     # iterasi jauh lebih banyak (dulu 500)

    for _ in range(n_iter):
        # [FIX 4] Pilih operator neighbourhood secara acak
        if random.random() < 0.7:
            new_seq = neighbour_swap(current_seq)
        else:
            new_seq = neighbour_insert(current_seq)

        new_score, _, _ = eval_sequence(new_seq)

        # [FIX 2] Delta dihitung dari current_score (bukan best_score)
        delta = new_seq and (new_score - current_score)
        delta = new_score - current_score

        if delta < 0 or (T_sa > 1e-10 and random.random() < math.exp(-delta / T_sa)):
            current_seq   = new_seq
            current_score = new_score
            if new_score < best_score:
                best_seq   = new_seq.copy()
                best_score = new_score

        T_sa *= cooling_rate

    _, final_sched, final_end = eval_sequence(best_seq)
    return best_score, final_sched, final_end


# ==========================================
# 8. SIDEBAR
# ==========================================
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2043/2043236.png", width=60)
    st.header("⚙️ Konfigurasi Sistem")

    with st.expander("📥 Download Template Data"):
        st.markdown("Gunakan format CSV ini untuk data baru.")
        template_df = pd.DataFrame({
            'id pesanan'       : ['ORD-01', 'ORD-02'],
            'jenis produk'     : ['Kaos', 'Kemeja'],
            'qty'              : [100, 50],
            'due date (tanggal)': ['15/05/2026', '20/05/2026'],
            'furing'           : [0, 1],
            'sablon'           : [1, 0],
            'dtf'              : [0, 0],
            'bordir'           : [0, 1],
            'pasang kancing'   : [0, 1]
        })
        csv_template = template_df.to_csv(index=False).encode('utf-8')
        st.download_button("Download Template.csv", csv_template, "Template_Order_Pabrik.csv", "text/csv")

    uploaded_file = st.file_uploader("1. Upload Data Order (CSV / Excel)", type=['csv', 'xlsx', 'xls'])

    start_date_input = st.date_input("2. Tanggal Mulai Produksi", datetime.today())
    start_date = datetime.combine(start_date_input, datetime.min.time()).replace(hour=8, minute=30)

    st.subheader("🛠️ Analisis Sensitivitas")
    use_custom = st.checkbox("Ubah Parameter Kapasitas Default", help="Centang untuk simulasi operator sakit/mesin rusak.")

    # Default resources
    res = {m: 1 for m in STATIONS}
    res['3. Jahit_KemejaJaket'] = 3
    res['8. Buang_Benang']      = 2
    setup_time_val = 0.0

    if use_custom:
        with st.container(border=True):
            setup_time_val              = st.number_input("Waktu Setup Antar Order (Menit)", 0.0, 60.0, 0.0, 5.0)
            res['1. Potong']            = st.number_input("Operator Potong", 1, 10, 1)
            res['2. Jahit_KaosPolo']    = st.number_input("Tim Jahit Kaos/Polo", 1, 10, 1)
            res['3. Jahit_KemejaJaket'] = st.number_input("Tim Jahit Kemeja/Jaket", 1, 10, 3)
            res['4. Sablon']            = st.number_input("Stasiun Sablon", 1, 10, 1)
            res['5. DTF']               = st.number_input("Stasiun DTF", 1, 10, 1)
            res['6. Bordir']            = st.number_input("Stasiun Bordir", 1, 10, 1)
            res['7. Pasang_Kancing']    = st.number_input("Operator Pasang Kancing", 1, 10, 1)
            res['8. Buang_Benang']      = st.number_input("Operator Buang Benang", 1, 10, 2)
            res['9. Lipat']             = st.number_input("Operator Lipat", 1, 10, 1)
            res['10. Packing']          = st.number_input("Operator Packing", 1, 10, 1)

    milp_time_limit = st.slider(
        "⏱️ Batas Waktu MILP (detik)", min_value=60, max_value=600, value=300, step=30,
        help="Waktu maksimum solver MILP berpikir. Lebih lama = peluang solusi lebih baik."
    )

    run_button = st.button("🚀 JALANKAN OPTIMASI", type="primary", use_container_width=True)


# ==========================================
# 9. MAIN AREA
# ==========================================
if uploaded_file is not None:
    try:
        df = load_order_file(uploaded_file)
        df['Bulan-Tahun'] = df['due date (tanggal)'].dt.strftime('%B %Y')

        with st.container(border=True):
            c1, c2 = st.columns(2)
            with c1:
                bulan_pilih = st.selectbox("Filter Bulan Due Date:", ["Semua"] + list(df['Bulan-Tahun'].unique()))
            with c2:
                sortir = st.selectbox("Urutkan Berdasarkan:", ["Due Date Terdekat", "Due Date Terjauh"])

        df_display = df.copy() if bulan_pilih == "Semua" else df[df['Bulan-Tahun'] == bulan_pilih].copy()
        df_display = df_display.sort_values(by='due date (tanggal)', ascending=(sortir == "Due Date Terdekat"))

        if "Pilih" not in df_display.columns:
            df_display.insert(0, "Pilih", False)
        if "Priority" not in df_display.columns:
            df_display.insert(1, "Priority", False)

        st.subheader("📋 Pemilihan Order Pending")
        st.info("💡 Centang 'Pilih' untuk memproses order. Centang 'Priority' untuk memberi bobot penalti besar (order VIP).")

        edited_df = st.data_editor(
            df_display.drop(columns=['Bulan-Tahun']),
            hide_index=True,
            use_container_width=True
        )

        df_pool = edited_df[edited_df["Pilih"] == True].copy()

        # ==========================================
        # 10. RUN OPTIMIZATION
        # ==========================================
        if run_button:
            if len(df_pool) == 0:
                st.warning("⚠️ Centang minimal 1 pesanan untuk diproses!")
            else:
                with st.status("⚙️ Menjalankan Engine Optimasi Pabrik...", expanded=True) as status_ui:

                    # --- TAHAP 1: Kalkulasi waktu proses & target ---
                    status_ui.update(label="1/4 Mengkalkulasi Kapasitas & Routing Dinamis...", state="running")

                    df_pool = df_pool.copy()
                    df_pool['target_dt'] = df_pool['due date (tanggal)'].apply(
                        lambda x: x.replace(hour=17, minute=30, second=0, microsecond=0)
                    )

                    # [FIX 7] Gunakan fungsi hitung_target_menit yang diperbaiki
                    df_pool['target_menit'] = df_pool['target_dt'].apply(
                        lambda x: hitung_target_menit(x, start_date)
                    )

                    jobs_raw = df_pool.to_dict('records')
                    job_ids  = [str(j['id pesanan']) for j in jobs_raw]

                    P = {str(j['id pesanan']): hitung_waktu_proses(j, res, setup_time_val) for j in jobs_raw}
                    D = {str(j['id pesanan']): j['target_menit'] for j in jobs_raw}
                    W = {str(j['id pesanan']): 10000 if j['Priority'] else 1 for j in jobs_raw}

                    # --- TAHAP 2: Simulated Annealing ---
                    status_ui.update(label="2/4 Mesin SA mencari solusi awal (8.000 iterasi)...", state="running")
                    sa_score, sa_sched, sa_end = run_simulated_annealing(job_ids, P, D, W)
                    st.info(f"🔵 SA selesai. Skor penalti SA: **{sa_score:,.2f}**")

                    # --- TAHAP 3: MILP ---
                    status_ui.update(label=f"3/4 Solver MILP berpikir (maks {milp_time_limit} detik)...", state="running")

                    prob     = pulp.LpProblem("JobShop_Garment", pulp.LpMinimize)
                    S        = pulp.LpVariable.dicts("Start", (job_ids, STATIONS), lowBound=0, cat='Continuous')
                    # [FIX 8] Rename var tardiness → Tard_var (hindari bentrok nama dengan loop var T)
                    Tard_var = pulp.LpVariable.dicts("Tard", job_ids, lowBound=0, cat='Continuous')

                    # [FIX 5] BigM dinamis: 2× total durasi maksimum semua stasiun
                    max_total_dur = sum(
                        max((P[i][m] for i in job_ids), default=0)
                        for m in STATIONS
                    )
                    BigM = max(int(max_total_dur * 2), 10000)
                    st.caption(f"ℹ️ BigM yang digunakan: {BigM:,} menit (dihitung dinamis dari data)")

                    # [FIX 8] Variabel biner sequencing: hanya buat untuk pasangan job yang share mesin
                    active_pairs = {}   # (i, j, m) → LpVariable
                    for m in STATIONS:
                        active_jobs_m = [i for i in job_ids if P[i][m] > 0]
                        for idx_i in range(len(active_jobs_m)):
                            for idx_j in range(idx_i + 1, len(active_jobs_m)):
                                i = active_jobs_m[idx_i]
                                j = active_jobs_m[idx_j]
                                var = pulp.LpVariable(f"Y_{i}_{j}_{m}", cat='Binary')
                                active_pairs[(i, j, m)] = var

                    # Fungsi objektif: minimasi total weighted tardiness
                    prob += pulp.lpSum([W[i] * Tard_var[i] for i in job_ids])

                    # Constraint 1: Precedence (urutan stasiun dalam satu job)
                    for i in job_ids:
                        rute_aktif = [m for m in STATIONS if P[i][m] > 0]
                        for idx in range(1, len(rute_aktif)):
                            st_sebelum  = rute_aktif[idx - 1]
                            st_sekarang = rute_aktif[idx]
                            prob += S[i][st_sekarang] >= S[i][st_sebelum] + P[i][st_sebelum]

                        # Constraint 2: Tardiness definition
                        if rute_aktif:
                            st_terakhir = rute_aktif[-1]
                            prob += Tard_var[i] >= (S[i][st_terakhir] + P[i][st_terakhir]) - D[i]

                    # Constraint 3: No-overlap (satu mesin, dua job)
                    for (i, j, m), y_var in active_pairs.items():
                        prob += S[j][m] >= S[i][m] + P[i][m] - BigM * y_var
                        prob += S[i][m] >= S[j][m] + P[j][m] - BigM * (1 - y_var)

                    # Solve
                    prob.solve(pulp.PULP_CBC_CMD(timeLimit=milp_time_limit, msg=0))

                    status_ui.update(label="4/4 Membandingkan & Finalisasi...", state="running")

                    milp_status   = pulp.LpStatus[prob.status]
                    obj_val       = pulp.value(prob.objective)

                    # [FIX 6] Terima 'Optimal' DAN 'Feasible' (status MILP saat time limit habis tapi ada solusi)
                    milp_feasible = milp_status in ['Optimal', 'Feasible'] and obj_val is not None
                    milp_score    = float(obj_val) if milp_feasible else float('inf')

                    st.info(f"🟠 MILP selesai. Status: **{milp_status}** | Skor penalti MILP: **{milp_score:,.2f}**")

                    # --- Showdown: pilih pemenang ---
                    if milp_feasible and milp_score <= sa_score:
                        pemenang     = f"MILP — {milp_status} (Presisi Tinggi)"
                        jadwal_final = []
                        waktu_selesai_dict = {}

                        for i in job_ids:
                            rute = [m for m in STATIONS if P[i][m] > 0]
                            if rute:
                                st_last = rute[-1]
                                waktu_selesai_dict[i] = S[i][st_last].varValue + P[i][st_last]
                            else:
                                waktu_selesai_dict[i] = 0
                            for m in rute:
                                jadwal_final.append({
                                    'job'  : i,
                                    'm'    : m,
                                    'start': round(S[i][m].varValue or 0, 2),
                                    'dur'  : P[i][m]
                                })
                        st.success(f"🏆 Pemenang: **Solver MILP** (Skor: {milp_score:,.2f} vs SA: {sa_score:,.2f})")
                    else:
                        pemenang           = "Simulated Annealing (Solusi Metaheuristik)"
                        jadwal_final       = sa_sched
                        waktu_selesai_dict = sa_end
                        reason = "SA lebih baik" if milp_feasible else "MILP tidak menemukan solusi feasible"
                        st.success(f"🏆 Pemenang: **SA** ({reason}) (Skor: {sa_score:,.2f})")

                    sanity_log = jalankan_sanity_check(jadwal_final)
                    status_ui.update(label="✅ Optimasi Selesai!", state="complete")

                # ==========================================
                # 11. POST-PROCESSING
                # ==========================================
                laporan_order  = []
                jadwal_gantt   = []
                jadwal_operator = []
                pesanan_telat  = 0

                for i in job_ids:
                    target_nyata  = df_pool[df_pool['id pesanan'].astype(str) == i]['target_dt'].iloc[0]
                    selesai_nyata = konversi_ke_jam_dinding(waktu_selesai_dict[i], start_date)
                    is_priority   = "⭐ Ya" if W[i] > 1 else "Tidak"
                    selisih_menit = (selesai_nyata - target_nyata).total_seconds() / 60
                    status        = 'Telat' if selisih_menit > 0 else 'Tepat Waktu'

                    if selisih_menit > 0:
                        pesanan_telat += 1

                    laporan_order.append({
                        'ID Pesanan'      : i,
                        'Prioritas'       : is_priority,
                        'Target Selesai'  : target_nyata.strftime('%d-%b-%y %H:%M'),
                        'Estimasi Selesai': selesai_nyata.strftime('%d-%b-%y %H:%M'),
                        'Status'          : status,
                        'Telat (Hari)'    : math.ceil(max(0, selisih_menit) / 450)
                    })

                for tugas in jadwal_final:
                    qty_row = df_pool[df_pool['id pesanan'].astype(str) == tugas['job']]['qty'].iloc[0]

                    jadwal_operator.append({
                        'Stasiun Kerja': tugas['m'],
                        'ID Pesanan'   : tugas['job'],
                        'Qty'          : qty_row,
                        'Mulai'        : konversi_ke_jam_dinding(tugas['start'], start_date).strftime('%d-%b-%y %H:%M'),
                        'Selesai'      : konversi_ke_jam_dinding(tugas['start'] + tugas['dur'], start_date).strftime('%d-%b-%y %H:%M')
                    })

                    pecahan_waktu = pecah_balok_gantt(tugas['start'], tugas['dur'], start_date)
                    for potong in pecahan_waktu:
                        jadwal_gantt.append({
                            'Stasiun Kerja' : tugas['m'],
                            'ID Pesanan'    : tugas['job'],
                            'Qty'           : qty_row,
                            'Mulai'         : potong['start_nyata'],
                            'Selesai'       : potong['end_nyata'],
                            'Durasi (Menit)': round(potong['durasi_potongan'], 2)
                        })

                df_gantt   = pd.DataFrame(jadwal_gantt)
                df_laporan = pd.DataFrame(laporan_order).sort_values(
                    by=['Status', 'Estimasi Selesai'], ascending=[False, True]
                )
                df_op = pd.DataFrame(jadwal_operator)

                # ==========================================
                # 12. DASHBOARD
                # ==========================================
                st.markdown('<div class="metric-card">', unsafe_allow_html=True)
                col1, col2, col3, col4 = st.columns(4)
                col1.metric("📦 Total Pesanan", len(job_ids))
                col2.metric("✅ Tepat Waktu", len(job_ids) - pesanan_telat)
                col3.metric("🚨 Terlambat", pesanan_telat, delta_color="inverse")
                col4.metric("🏆 Metode Terbaik", pemenang.split(" ")[0])
                st.markdown('</div><br>', unsafe_allow_html=True)

                tab1, tab2, tab3, tab4 = st.tabs([
                    "📊 Gantt Chart Mesin",
                    "📑 Laporan Manajemen",
                    "👨‍🔧 Lembar Kerja Operator",
                    "🔎 Log Sistem & Sanity Check"
                ])

                with tab1:
                    st.markdown(f"**Jadwal Master Produksi** — Dihasilkan oleh: *{pemenang}*")
                    fig = px.timeline(
                        df_gantt,
                        x_start="Mulai",
                        x_end="Selesai",
                        y="Stasiun Kerja",
                        color="ID Pesanan",
                        hover_data=["Durasi (Menit)", "Qty"]
                    )
                    fig.update_yaxes(categoryorder="array", categoryarray=STATIONS[::-1])
                    fig.update_layout(
                        height=500,
                        plot_bgcolor='rgba(0,0,0,0)',
                        paper_bgcolor='rgba(0,0,0,0)'
                    )
                    st.plotly_chart(fig, use_container_width=True)

                with tab2:
                    st.markdown("**Status Penyelesaian Order per Tenggat Waktu**")

                    def color_status(val):
                        return 'background-color: #F87171; color: white' if val == 'Telat' \
                               else 'background-color: #34D399; color: white'

                    st.dataframe(
                        df_laporan.style.map(color_status, subset=['Status']),
                        use_container_width=True,
                        height=400
                    )

                with tab3:
                    st.markdown("**Instruksi Kerja (Work Order) per Stasiun Kerja**")
                    for stasiun in sorted(df_op['Stasiun Kerja'].unique()):
                        with st.expander(f"📁 Buka Jadwal: {stasiun}"):
                            st.dataframe(
                                df_op[df_op['Stasiun Kerja'] == stasiun].drop(columns=['Stasiun Kerja']),
                                hide_index=True,
                                use_container_width=True
                            )

                with tab4:
                    st.markdown("**Transparansi Algoritma (Audit Otomatis)**")
                    st.info("Log ini membuktikan bahwa jadwal yang dihasilkan telah lolos uji logika batas pabrik.")
                    st.code(sanity_log, language="text")

                    if "PASSED" in sanity_log:
                        st.success("✅ Verifikasi berhasil. Tidak ada pelanggaran batas produksi.")
                    else:
                        st.error("🚨 Verifikasi gagal. Terdapat bentrok stasiun atau pelanggaran urutan.")

                st.divider()
                st.subheader("📥 Unduh Rekap Excel")

                buffer = io.BytesIO()
                with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                    df_laporan.to_excel(writer, sheet_name='Laporan Manajemen', index=False)
                    df_op.to_excel(writer, sheet_name='Jadwal per Stasiun', index=False)

                st.download_button(
                    label="Download Laporan Format .xlsx",
                    data=buffer.getvalue(),
                    file_name=f"Jadwal_Pabrik_{datetime.now().strftime('%d%b%Y')}.xlsx",
                    mime="application/vnd.ms-excel",
                    type="secondary"
                )

    except Exception as e:
        st.error(f"🚨 Terjadi kesalahan sistem: {e}")
        import traceback
        st.code(traceback.format_exc(), language="text")
        st.write("Pastikan library openpyxl & pulp sudah terinstall.")
else:
    st.info("👈 Silakan unggah file CSV / Excel di panel samping untuk memulai simulasi.")