# -*- coding: utf-8 -*-
"""appppp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfMWQxPJmgQ9IFfLQrBEDk1gFyTdqZp7
"""

import streamlit as st
import pandas as pd
import pulp
import math
import random
import io
from datetime import datetime, timedelta
import plotly.express as px

# ==========================================
# 1. KONFIGURASI HALAMAN & STATE
# ==========================================
st.set_page_config(page_title="DSS Penjadwalan Job Shop", layout="wide", page_icon="🏭")

st.markdown("""
    <style>
    .main-header { font-size: 2.5rem; font-weight: 700; color: #1E3A8A; margin-bottom: 0px; }
    .sub-header { font-size: 1.2rem; color: #64748B; margin-bottom: 20px; }
    .metric-card { background-color: #F8FAFC; border-radius: 10px; padding: 20px; border: 1px solid #E2E8F0; }
    </style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-header">🏭 DSS: Optimasi Penjadwalan Produksi</p>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">Sistem Penjadwalan Cerdas dengan Routing Dinamis (OPC), AI Solver, dan Analisis Sensitivitas.</p>', unsafe_allow_html=True)
st.divider()

STATIONS = [
    '1. Potong', '2. Jahit_KaosPolo', '3. Jahit_KemejaJaket',
    '4. Sablon', '5. DTF', '6. Bordir', '7. Inspeksi_QC',
    '8. Pasang_Kancing', '9. Buang_Benang', '10. Lipat', '11. Packing'
]

REQUIRED_COLUMNS = [
    'id pesanan', 'jenis produk', 'qty', 'due date (tanggal)',
    'furing', 'sablon', 'dtf', 'bordir', 'pasang kancing'
]

BINARY_COLUMNS = ['furing', 'sablon', 'dtf', 'bordir', 'pasang kancing']


# ==========================================
# 2. HELPER: LOAD & CLEAN DATA
# ==========================================
def load_order_file(uploaded_file):
    file_name = uploaded_file.name.lower()

    if file_name.endswith('.csv'):
        df = pd.read_csv(uploaded_file)
    elif file_name.endswith('.xlsx') or file_name.endswith('.xls'):
        df = pd.read_excel(uploaded_file)
    else:
        raise ValueError("Format file tidak didukung. Gunakan CSV atau Excel.")

    # rapikan nama kolom
    df.columns = df.columns.str.lower().str.strip()

    # validasi kolom wajib
    missing_cols = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Kolom berikut belum ada / salah nama: {missing_cols}")

    # ambil hanya kolom penting agar aman
    df = df[REQUIRED_COLUMNS].copy()

    # bersihkan string
    df['id pesanan'] = df['id pesanan'].astype(str).str.strip()
    df['jenis produk'] = df['jenis produk'].astype(str).str.strip().str.lower()

    # standardisasi nama produk
    mapping_jenis = {
        'kaos': 'kaos',
        'polo': 'polo',
        'kemeja': 'kemeja',
        'jaket': 'jaket'
    }
    df['jenis produk'] = df['jenis produk'].replace(mapping_jenis)

    unknown_jenis = sorted(set(df['jenis produk']) - set(mapping_jenis.values()))
    if unknown_jenis:
        raise ValueError(f"Jenis produk tidak dikenali: {unknown_jenis}")

    # qty numeric
    df['qty'] = pd.to_numeric(df['qty'], errors='coerce')

    # binary columns -> numeric 0/1
    for col in BINARY_COLUMNS:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # parse due date: dataset baru formatnya seperti 2/8/2025, jadi dayfirst=True
    df['due date (tanggal)'] = pd.to_datetime(
        df['due date (tanggal)'],
        errors='coerce',
        dayfirst=True
    )

    # validasi null setelah coercion
    if df[['id pesanan', 'jenis produk', 'qty', 'due date (tanggal)'] + BINARY_COLUMNS].isnull().any().any():
        bad_rows = df[df[['qty', 'due date (tanggal)'] + BINARY_COLUMNS].isnull().any(axis=1)]
        raise ValueError(
            "Ada data kosong / invalid setelah dibaca. "
            "Cek terutama kolom qty, due date (tanggal), dan kolom 0/1.\n"
            f"Baris bermasalah: {bad_rows.index.tolist()}"
        )

    # validasi qty > 0
    if (df['qty'] <= 0).any():
        bad_ids = df.loc[df['qty'] <= 0, 'id pesanan'].tolist()
        raise ValueError(f"Ada qty <= 0 pada order: {bad_ids}")

    # validasi binary harus 0/1
    for col in BINARY_COLUMNS:
        invalid_vals = df.loc[~df[col].isin([0, 1]), col].unique().tolist()
        if invalid_vals:
            raise ValueError(f"Kolom '{col}' hanya boleh berisi 0 atau 1. Nilai invalid: {invalid_vals}")

    return df


# ==========================================
# 3. LOGIKA KAPASITAS & WAKTU
# ==========================================
def hitung_waktu_proses(row, resources, setup_time):
    qty = row['qty']
    jenis = str(row['jenis produk']).lower()
    furing = row['furing']

    P = {m: 0.0 for m in STATIONS}

    # Potong
    cap_potong = 1000
    if jenis in ['kemeja', 'jaket']:
        cap_potong = 125 if furing == 1 else 250
    P['1. Potong'] = (qty / (cap_potong * resources['1. Potong'])) * 450

    # Jahit
    if jenis in ['kaos', 'polo']:
        cap_jahit = 112.5 if jenis == 'kaos' else 55
        P['2. Jahit_KaosPolo'] = (qty / (cap_jahit * resources['2. Jahit_KaosPolo'])) * 450
    elif jenis in ['kemeja', 'jaket']:
        base_cap = 13.5 if jenis == 'kemeja' else 11.0
        if furing == 1:
            base_cap *= (2 / 3)
        P['3. Jahit_KemejaJaket'] = (qty / (base_cap * resources['3. Jahit_KemejaJaket'])) * 450

    # Proses tambahan
    if row['sablon'] == 1:
        P['4. Sablon'] = (qty / (700 * resources['4. Sablon'])) * 450
    if row['dtf'] == 1:
        P['5. DTF'] = (qty / (750 * resources['5. DTF'])) * 450
    if row['bordir'] == 1:
        P['6. Bordir'] = (qty / (442.5 * resources['6. Bordir'])) * 450

    # QC
    P['7. Inspeksi_QC'] = 0.0

    # Pasang kancing
    if row['pasang kancing'] == 1 and jenis != 'kaos':
        cap_kancing = 400 if jenis == 'polo' else 125
        P['8. Pasang_Kancing'] = (qty / (cap_kancing * resources['8. Pasang_Kancing'])) * 450

    # Finishing
    cap_benang = 166.67 if furing == 1 else 500
    P['9. Buang_Benang'] = (qty / (cap_benang * resources['9. Buang_Benang'])) * 450
    P['10. Lipat'] = (qty / (500 * resources['10. Lipat'])) * 450
    P['11. Packing'] = (qty / (500 * resources['11. Packing'])) * 450

    # setup time hanya ditambahkan kalau stasiun aktif
    for m in STATIONS:
        if P[m] > 0:
            P[m] += setup_time

    return P


def konversi_ke_jam_dinding(menit_efektif, start_date):
    hari_ke = int(menit_efektif // 450)
    sisa_menit = menit_efektif % 450
    current_date = start_date
    hari_tambahan = 0

    while hari_tambahan < hari_ke:
        current_date += timedelta(days=1)
        if current_date.weekday() != 6:  # Minggu libur
            hari_tambahan += 1

    if current_date.weekday() == 6:
        current_date += timedelta(days=1)

    if sisa_menit <= 180:
        return current_date.replace(hour=8, minute=30) + timedelta(minutes=sisa_menit)
    else:
        return current_date.replace(hour=8, minute=30) + timedelta(minutes=sisa_menit + 90)


def pecah_balok_gantt(start_efektif, durasi, start_date):
    blocks = []
    menit_tersisa = durasi
    current_efektif = start_efektif

    while menit_tersisa > 0.01:
        menit_di_hari = current_efektif % 450
        if menit_di_hari < 180:
            chunk = min(menit_tersisa, 180 - menit_di_hari)
        else:
            chunk = min(menit_tersisa, 450 - menit_di_hari)

        blocks.append({
            'start_nyata': konversi_ke_jam_dinding(current_efektif, start_date),
            'end_nyata': konversi_ke_jam_dinding(current_efektif + chunk, start_date),
            'durasi_potongan': chunk
        })

        current_efektif += chunk
        menit_tersisa -= chunk

    return blocks


# ==========================================
# 4. SANITY CHECK
# ==========================================
def jalankan_sanity_check(jadwal_final):
    log = []
    log.append("============================================================")
    log.append("🔍 [SYSTEM LOG] MEMULAI SANITY CHECK (VERIFIKASI LOGIKA)")
    log.append("============================================================\n")

    err_overlap, err_presedens = False, False

    log.append("[1/3] Memeriksa Overlap Kapasitas Mesin...")
    stasiun_list = set([t['m'] for t in jadwal_final])
    for st_name in stasiun_list:
        tugas_st = sorted([t for t in jadwal_final if t['m'] == st_name], key=lambda x: x['start'])
        for i in range(1, len(tugas_st)):
            prev, curr = tugas_st[i - 1], tugas_st[i]
            if round(curr['start'] - (prev['start'] + prev['dur']), 2) < 0:
                log.append(f"  ❌ OVERLAP di {st_name}: Order {prev['job']} & {curr['job']} bentrok!")
                err_overlap = True
    if not err_overlap:
        log.append("  ✔️ LULUS: Tidak ada order tumpang tindih.")

    log.append("\n[2/3] Memeriksa Presedensi (Urutan Stasiun per Pesanan)...")
    job_list = set([t['job'] for t in jadwal_final])
    for job in job_list:
        tugas_job = sorted([t for t in jadwal_final if t['job'] == job], key=lambda x: x['start'])
        for i in range(1, len(tugas_job)):
            prev, curr = tugas_job[i - 1], tugas_job[i]
            if round(curr['start'] - (prev['start'] + prev['dur']), 2) < 0:
                log.append(f"  ❌ ERROR URUTAN Order {job}: {curr['m']} mulai sebelum {prev['m']} selesai!")
                err_presedens = True
    if not err_presedens:
        log.append("  ✔️ LULUS: Seluruh urutan pengerjaan sudah benar.")

    log.append("\n[3/3] Memeriksa Pelanggaran Istirahat & Libur...")
    log.append("  ✔️ LULUS: Konversi waktu menjamin tidak ada jadwal aktif di jam istirahat/hari libur.")

    log.append("\n============================================================")
    if err_overlap or err_presedens:
        log.append("🚨 SANITY CHECK GAGAL! Ditemukan pelanggaran.")
    else:
        log.append("✅ SANITY CHECK PASSED! Rute Dinamis & Jadwal Valid.")
    log.append("============================================================")

    return "\n".join(log)


# ==========================================
# 5. SIMULATED ANNEALING
# ==========================================
def run_simulated_annealing(jobs, P_dict, D_dict, W_dict):
    def eval_sequence(seq):
        m_avail = {m: 0.0 for m in STATIONS}
        j_avail = {j: 0.0 for j in seq}
        total_penalti = 0
        schedule = []

        for j in seq:
            rute_aktif = [m for m in STATIONS if P_dict[j][m] > 0]
            for m in rute_aktif:
                dur = P_dict[j][m]
                start = max(m_avail[m], j_avail[j])
                end = start + dur
                m_avail[m], j_avail[j] = end, end
                schedule.append({'job': j, 'm': m, 'start': start, 'dur': dur})

            tard = max(0, j_avail[j] - D_dict[j])
            total_penalti += tard * W_dict[j]

        return total_penalti, schedule, j_avail

    current_seq = sorted(jobs, key=lambda x: D_dict[x])
    best_seq = current_seq.copy()
    best_score, _, _ = eval_sequence(best_seq)

    T = 1000
    cooling_rate = 0.95

    for _ in range(500):
        new_seq = current_seq.copy()
        idx1, idx2 = random.sample(range(len(new_seq)), 2)
        new_seq[idx1], new_seq[idx2] = new_seq[idx2], new_seq[idx1]

        new_score, _, _ = eval_sequence(new_seq)

        if new_score < best_score or random.random() < math.exp((best_score - new_score) / T):
            current_seq = new_seq
            if new_score < best_score:
                best_seq, best_score = new_seq.copy(), new_score

        T *= cooling_rate

    _, final_sched, final_end = eval_sequence(best_seq)
    return best_score, final_sched, final_end


# ==========================================
# 6. SIDEBAR
# ==========================================
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2043/2043236.png", width=60)
    st.header("⚙️ Konfigurasi Sistem")

    with st.expander("📥 Download Template Data"):
        st.markdown("Gunakan format CSV ini untuk data baru.")
        template_df = pd.DataFrame({
            'id pesanan': ['ORD-01', 'ORD-02'],
            'jenis produk': ['Kaos', 'Kemeja'],
            'qty': [100, 50],
            'due date (tanggal)': ['15/05/2026', '20/05/2026'],
            'furing': [0, 1],
            'sablon': [1, 0],
            'dtf': [0, 0],
            'bordir': [0, 1],
            'pasang kancing': [0, 1]
        })
        csv_template = template_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            "Download Template.csv",
            csv_template,
            "Template_Order_Pabrik.csv",
            "text/csv"
        )

    uploaded_file = st.file_uploader("1. Upload Data Order (CSV / Excel)", type=['csv', 'xlsx', 'xls'])

    start_date_input = st.date_input("2. Tanggal Mulai Produksi", datetime.today())
    start_date = datetime.combine(start_date_input, datetime.min.time()).replace(hour=8, minute=30)

    st.subheader("🛠️ Analisis Sensitivitas")
    use_custom = st.checkbox("Ubah Parameter Kapasitas Default", help="Centang untuk simulasi operator sakit/mesin rusak.")

    res = {m: 1 for m in STATIONS}
    res['3. Jahit_KemejaJaket'] = 3
    res['9. Buang_Benang'] = 2
    setup_time_val = 0.0

    if use_custom:
        with st.container(border=True):
            setup_time_val = st.number_input("Waktu Setup Antar Order (Menit)", 0.0, 60.0, 0.0, 5.0)
            res['1. Potong'] = st.number_input("Operator Potong", 1, 10, 1)
            res['2. Jahit_KaosPolo'] = st.number_input("Tim Jahit Kaos", 1, 10, 1)
            res['3. Jahit_KemejaJaket'] = st.number_input("Tim Jahit Kemeja", 1, 10, 3)
            res['4. Sablon'] = st.number_input("Stasiun Sablon", 1, 10, 1)

    run_button = st.button("🚀 JALANKAN OPTIMASI", type="primary", use_container_width=True)


# ==========================================
# 7. MAIN AREA
# ==========================================
if uploaded_file is not None:
    try:
        df = load_order_file(uploaded_file)

        df['Bulan-Tahun'] = df['due date (tanggal)'].dt.strftime('%B %Y')

        with st.container(border=True):
            c1, c2 = st.columns(2)
            with c1:
                bulan_pilih = st.selectbox("Filter Bulan Due Date:", ["Semua"] + list(df['Bulan-Tahun'].unique()))
            with c2:
                sortir = st.selectbox("Urutkan Berdasarkan:", ["Due Date Terdekat", "Due Date Terjauh"])

        df_display = df.copy() if bulan_pilih == "Semua" else df[df['Bulan-Tahun'] == bulan_pilih].copy()
        df_display = df_display.sort_values(by='due date (tanggal)', ascending=(sortir == "Due Date Terdekat"))

        if "Pilih" not in df_display.columns:
            df_display.insert(0, "Pilih", False)
        if "Priority" not in df_display.columns:
            df_display.insert(1, "Priority", False)

        st.subheader("📋 Pemilihan Order Pending")
        st.info("💡 Centang 'Pilih' untuk memproses order. Centang 'Priority' untuk memberi penalti besar pada pesanan penting.")

        edited_df = st.data_editor(
            df_display.drop(columns=['Bulan-Tahun']),
            hide_index=True,
            use_container_width=True
        )

        df_pool = edited_df[edited_df["Pilih"] == True].copy()

        # ==========================================
        # 8. RUN OPTIMIZATION
        # ==========================================
        if run_button:
            if len(df_pool) == 0:
                st.warning("⚠️ Centang minimal 1 pesanan untuk diproses!")
            else:
                with st.status("⚙️ Menjalankan Engine Optimasi Pabrik...", expanded=True) as status_ui:
                    status_ui.update(label="1/4 Mengkalkulasi Kapasitas & Routing Dinamis...", state="running")

                    df_pool['target_dt'] = df_pool['due date (tanggal)'].apply(
                        lambda x: x.replace(hour=17, minute=30)
                    )

                    def hitung_target_menit(target_dt, start_dt):
                        if target_dt < start_dt:
                            return 0

                        current = start_dt
                        total_menit = 0

                        while current.date() < target_dt.date():
                            if current.weekday() != 6:
                                total_menit += 450
                            current += timedelta(days=1)

                        if target_dt.weekday() != 6:
                            total_menit += 450

                        return total_menit

                    df_pool['target_menit'] = df_pool['target_dt'].apply(lambda x: hitung_target_menit(x, start_date))

                    jobs_raw = df_pool.to_dict('records')
                    job_ids = [str(j['id pesanan']) for j in jobs_raw]

                    P = {str(j['id pesanan']): hitung_waktu_proses(j, res, setup_time_val) for j in jobs_raw}
                    D = {str(j['id pesanan']): j['target_menit'] for j in jobs_raw}
                    W = {str(j['id pesanan']): 10000 if j['Priority'] else 1 for j in jobs_raw}

                    status_ui.update(label="2/4 Mesin Metaheuristik SA mencari jalur awal...", state="running")
                    sa_score, sa_sched, sa_end = run_simulated_annealing(job_ids, P, D, W)

                    status_ui.update(label="3/4 Mesin AI MILP mencari jalur presisi...", state="running")

                    prob = pulp.LpProblem("JobShop_Garment", pulp.LpMinimize)
                    S = pulp.LpVariable.dicts("Start", (job_ids, STATIONS), lowBound=0, cat='Continuous')
                    T = pulp.LpVariable.dicts("Tard", job_ids, lowBound=0, cat='Continuous')
                    Y = pulp.LpVariable.dicts("Y", (job_ids, job_ids, STATIONS), cat='Binary')

                    BigM = 1000000

                    prob += pulp.lpSum([W[i] * T[i] for i in job_ids])

                    for i in job_ids:
                        rute_aktif = [m for m in STATIONS if P[i][m] > 0]

                        for idx in range(1, len(rute_aktif)):
                            st_sebelum = rute_aktif[idx - 1]
                            st_sekarang = rute_aktif[idx]
                            prob += S[i][st_sekarang] >= S[i][st_sebelum] + P[i][st_sebelum]

                        if len(rute_aktif) > 0:
                            st_terakhir = rute_aktif[-1]
                            prob += T[i] >= (S[i][st_terakhir] + P[i][st_terakhir]) - D[i]

                    for m in STATIONS:
                        for idx_i, i in enumerate(job_ids):
                            for idx_j, j in enumerate(job_ids):
                                if idx_i < idx_j and P[i][m] > 0 and P[j][m] > 0:
                                    prob += S[j][m] >= S[i][m] + P[i][m] - BigM * Y[i][j][m]
                                    prob += S[i][m] >= S[j][m] + P[j][m] - BigM * (1 - Y[i][j][m])

                    prob.solve(pulp.PULP_CBC_CMD(timeLimit=300, msg=0))

                    status_ui.update(label="4/4 Finalisasi & Sanity Check...", state="running")

                    milp_status = pulp.LpStatus[prob.status]
                    milp_score = pulp.value(prob.objective) if milp_status == 'Optimal' else float('inf')

                    if milp_status == 'Optimal' and milp_score <= sa_score:
                        pemenang = "MILP (Solusi Optimal/Presisi Mutlak)"
                        st.success(f"🏆 Pemenang: **Solver MILP**! (Skor Penalti: {milp_score})")
                        jadwal_final = []
                        waktu_selesai_dict = {}

                        for i in job_ids:
                            rute = [m for m in STATIONS if P[i][m] > 0]
                            waktu_selesai_dict[i] = S[i][rute[-1]].varValue + P[i][rute[-1]] if rute else 0
                            for m in rute:
                                jadwal_final.append({
                                    'job': i,
                                    'm': m,
                                    'start': round(S[i][m].varValue, 2),
                                    'dur': P[i][m]
                                })
                    else:
                        pemenang = "Simulated Annealing (Solusi Cepat)"
                        st.success(f"🏆 Pemenang: **Metaheuristik SA**! (Skor Penalti: {sa_score:.2f})")
                        jadwal_final = sa_sched
                        waktu_selesai_dict = sa_end

                    sanity_log = jalankan_sanity_check(jadwal_final)
                    status_ui.update(label="✅ Optimasi Selesai!", state="complete")

                # ==========================================
                # 9. POST-PROCESSING
                # ==========================================
                laporan_order = []
                jadwal_gantt = []
                jadwal_operator = []
                pesanan_telat = 0

                for i in job_ids:
                    target_nyata = df_pool[df_pool['id pesanan'].astype(str) == i]['target_dt'].iloc[0]
                    selesai_nyata = konversi_ke_jam_dinding(waktu_selesai_dict[i], start_date)

                    is_priority = "⭐ Ya" if W[i] > 1 else "Tidak"
                    selisih_menit = (selesai_nyata - target_nyata).total_seconds() / 60
                    status = 'Telat' if selisih_menit > 0 else 'Tepat Waktu'

                    if selisih_menit > 0:
                        pesanan_telat += 1

                    laporan_order.append({
                        'ID Pesanan': i,
                        'Prioritas': is_priority,
                        'Target Selesai': target_nyata.strftime('%d-%b-%y %H:%M'),
                        'Estimasi Selesai': selesai_nyata.strftime('%d-%b-%y %H:%M'),
                        'Status': status,
                        'Telat (Hari)': math.ceil(max(0, selisih_menit) / 540)
                    })

                for tugas in jadwal_final:
                    qty = df_pool[df_pool['id pesanan'].astype(str) == tugas['job']]['qty'].iloc[0]

                    jadwal_operator.append({
                        'Stasiun Kerja': tugas['m'],
                        'ID Pesanan': tugas['job'],
                        'Qty': qty,
                        'Mulai': konversi_ke_jam_dinding(tugas['start'], start_date).strftime('%d-%b-%y %H:%M'),
                        'Selesai': konversi_ke_jam_dinding(tugas['start'] + tugas['dur'], start_date).strftime('%d-%b-%y %H:%M')
                    })

                    pecahan_waktu = pecah_balok_gantt(tugas['start'], tugas['dur'], start_date)
                    for potong in pecahan_waktu:
                        jadwal_gantt.append({
                            'Stasiun Kerja': tugas['m'],
                            'ID Pesanan': tugas['job'],
                            'Qty': qty,
                            'Mulai': potong['start_nyata'],
                            'Selesai': potong['end_nyata'],
                            'Durasi (Menit)': round(potong['durasi_potongan'], 2)
                        })

                df_gantt = pd.DataFrame(jadwal_gantt)
                df_laporan = pd.DataFrame(laporan_order).sort_values(
                    by=['Status', 'Estimasi Selesai'],
                    ascending=[False, True]
                )
                df_op = pd.DataFrame(jadwal_operator)

                # ==========================================
                # 10. DASHBOARD
                # ==========================================
                st.markdown('<div class="metric-card">', unsafe_allow_html=True)
                col1, col2, col3 = st.columns(3)
                col1.metric("📦 Total Pesanan Terjadwal", len(job_ids))
                col2.metric("✅ Pesanan Tepat Waktu", len(job_ids) - pesanan_telat)
                col3.metric("🚨 Pesanan Terlambat", pesanan_telat, delta_color="inverse")
                st.markdown('</div><br>', unsafe_allow_html=True)

                tab1, tab2, tab3, tab4 = st.tabs([
                    "📊 Gantt Chart Mesin",
                    "📑 Laporan Manajemen",
                    "👨‍🔧 Lembar Kerja Operator",
                    "🔎 Log Sistem & Sanity Check"
                ])

                with tab1:
                    st.markdown(f"**Jadwal Master Produksi** - Menampilkan hasil *{pemenang}*")
                    fig = px.timeline(
                        df_gantt,
                        x_start="Mulai",
                        x_end="Selesai",
                        y="Stasiun Kerja",
                        color="ID Pesanan",
                        hover_data=["Durasi (Menit)", "Qty"]
                    )
                    fig.update_yaxes(categoryorder="array", categoryarray=STATIONS[::-1])
                    fig.update_layout(height=600, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
                    st.plotly_chart(fig, use_container_width=True)

                with tab2:
                    st.markdown("**Status Penyelesaian Order per Tenggat Waktu**")

                    def color_status(val):
                        return 'background-color: #F87171; color: white' if val == 'Telat' else 'background-color: #34D399; color: white'

                    st.dataframe(
                        df_laporan.style.map(color_status, subset=['Status']),
                        use_container_width=True,
                        height=400
                    )

                with tab3:
                    st.markdown("**Instruksi Kerja (Work Order) per Stasiun Kerja**")
                    for stasiun in sorted(df_op['Stasiun Kerja'].unique()):
                        with st.expander(f"📁 Buka Jadwal: {stasiun}"):
                            st.dataframe(
                                df_op[df_op['Stasiun Kerja'] == stasiun].drop(columns=['Stasiun Kerja']),
                                hide_index=True,
                                use_container_width=True
                            )

                with tab4:
                    st.markdown("**Transparansi Algoritma (Audit Otomatis)**")
                    st.info("Log ini membuktikan bahwa jadwal yang dihasilkan telah lolos uji logika batas pabrik.")
                    st.code(sanity_log, language="text")

                    if "PASSED" in sanity_log:
                        st.success("✅ Verifikasi berhasil. Tidak ada pelanggaran batas produksi pada jadwal ini.")
                    else:
                        st.error("🚨 Verifikasi gagal. Terdapat bentrok stasiun atau pelanggaran urutan.")

                st.divider()
                st.subheader("📥 Unduh Rekap Excel")

                buffer = io.BytesIO()
                with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                    df_laporan.to_excel(writer, sheet_name='Laporan Manajemen', index=False)
                    df_op.to_excel(writer, sheet_name='Jadwal per Stasiun', index=False)

                st.download_button(
                    label="Download Laporan Format .xlsx",
                    data=buffer.getvalue(),
                    file_name=f"Jadwal_Pabrik_{datetime.now().strftime('%d%b%Y')}.xlsx",
                    mime="application/vnd.ms-excel",
                    type="secondary"
                )

    except Exception as e:
        st.error(f"🚨 Terjadi kesalahan sistem saat membaca file/memproses: {e}")
        st.write("Pastikan library openpyxl sudah terinstall jika run lokal.")
else:
    st.info("👈 Silakan unggah file CSV / Excel di panel samping untuk memulai simulasi.")